### ISSUE TITLE
Import mnist1d could not be resolved(reportMissingImports) in Colab

### ISSUE THREAD

**Issue by zeeskore** [greydanus/mnist1d#10]
This worked last week, but today when I try to import mnist1d in Colab after running !git clone https://github.com/greydanus/mnist1d  I get no errors, but a yellow underline under import mnist1d  that says:

Import "mnist1d" could not be resolved(reportMissingImports) in Colab

Then:
args = mnist1d.data.get_dataset_args()  fails with AttributeError: module 'mnist1d' has no attribute 'data'

**Comment by greydanus** [comment]
Shoot! I just made some changes to this repo's structure this week which are responsible for the problem you're reporting. See https://github.com/greydanus/mnist1d/pull/9

I'll try and add a fix so that what you're doing doesn't throw an error. In the meantime, I recommend looking at the notebooks linked in the README, as they use some workarounds to call get_dataset_args()

You could also clone [this version](https://github.com/greydanus/mnist1d/tree/dfa02a194f6319be0b509374b1e1245083ce7ff5), which is the version you were using last week before all these changes. It should work as expected.

**Comment by zeeskore** [comment]
Issue seems to be with mnist1d/mnist1d subfolder which was not there after git clone https://github.com/greydanus/mnist1d  last week.  Import mnist1d works after I move all the files in mnist1d/mnist1d back to the top mnist1d folder.

**Comment by greydanus** [comment]
Try `pip install git+https://github.com/greydanus/mnist1d.git@master` and then in Python: `import mnist1d; mnist1d.get_dataset_args()`
