### ISSUE TITLE
Remote code execution possibility with pickled python objects

### ISSUE THREAD

**Issue by emiruz** [greydanus/mnist1d#6]
Hey thank you for this, but pickled objects in Python can be used to invoke remote code execution. It means I have to trust you in order to use this data. I'd be grateful if you'd consider distributing this data in some other way?

**Comment by greydanus** [comment]
Emiruz, this is a great point, I'll make the change. Although I can't say it'll be made in the next week or so. In the meantime, you'll either have to trust me or you could try unpickling in a Colab, then saving the file in some other format, and sending that file to me - in which case I could add that file to the repo and make the necessary code changes so that future researchers don't have the same dilemma. Thanks for bringing this issue up!

**Comment by emiruz** [comment]
The colab route is a good idea. I’ll give it go, repackage the data and send you a pull request when I get a minute.
________________________________

**Comment by breuderink** [comment]
I think that the data can be easily exported as a set of NumPy arrays:

```
np.savez_compressed('mnist1d_data.npz', **data)
np.savez_compressed('mnist1d_data_shuff.npz', **data_shuff)
```

Where could that be integrated? The [Building MNIST1D notebook](https://colab.research.google.com/github/greydanus/mnist1d/blob/master/building_mnist1d.ipynb) gives an error when I run it on Colab. It can't find `./static/human_q1.pkl`.

**Comment by greydanus** [comment]
Link to `./static/human_q1.pkl` has been fixed (see the _Building MNIST-1D_ notebook, notebook #2, for an example of how to load this properly) ; dataset can still be generated from scratch as documented in the README
