### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by dkobak** [greydanus/mnist1d#7]
Congrats on this dataset being prominently used in the Prince's ML textbook: https://udlbook.github.io/udlbook/ !

It made me wonder: was your paper published anywhere? It seems like it wasn't; but have you tried to publish it? I think it's really cool, so I am wondering if it kept getting rejected or if you haven't really tried to publish it.

**Comment by greydanus** [comment]
Thanks for the link. I spoke with Simon about this briefly. If I were teaching ML, it's definitely the introductory dataset I'd use as a teaching aid...but I am biased.

I never published it; it was a part 1 of a 5-paper (post) series that I was planning. I immediately moved on to the next part (studying growth with NCA) when I finished MNIST-1D. Since I moved out of research I have not returned to it.

Perhaps it should be submitted. Any idea as to what venue? The first thought that comes to mind is ICML 2024. If you're interested and want to do some work on it, you could potentially do a few more experiments and take the lead on submitting. Otherwise I'll try and find some time. No guarantees though

**Comment by dkobak** [comment]
Wow, I see. I ended up reading your blog posts for the whole evening yesterday :-) Amazing stuff, I loved the numerical action minimization.

Anyway, I think you basically have a finished paper and could send it to ICML as is. Of course with this kind of work one never knows what to expect. It may get super high scores, but it may as well get rejected as trivial and lacking novelty. But I think it's worth a try. If conference submission(s) fail(s), then I'd suggest JMLR where I'd expect it to get published without problems.

I'd be happy to provide some feedback for minor improvements, if you want.

I do have some ideas for further experiments, so if you prefer to extend the paper and collaborate on submission, I'd be happy to discuss! Let me write you an email about that.

**Comment by greydanus** [comment]
I'm very happy to hear that about my blog posts. I only work on/write about projects that I find fascinating and important, and nothing gives me more pleasure than hearing that someone else in the world felt the same spark. Makes all the hard work worthwhile.

I will respond to the rest of this via email thread.
